# Generated by Django 2.2 on 2021-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
