# Generated by Django 2.2 on 2021-03-28 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_is_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.IntegerField(null=True)),
                ('ending_time', models.IntegerField(null=True)),
                ('sat_day', models.BooleanField(default=False)),
                ('sun_day', models.BooleanField(default=False)),
                ('mon_day', models.BooleanField(default=False)),
                ('tues_day', models.BooleanField(default=False)),
                ('wed_day', models.BooleanField(default=False)),
                ('thurs_day', models.BooleanField(default=False)),
                ('fri_day', models.BooleanField(default=False)),
                ('doc_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Department')),
                ('doc_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
