# Generated by Django 2.2 on 2021-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ending_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='starting_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
