# Generated by Django 2.2 on 2021-04-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210328_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
