# Generated by Django 2.2 on 2021-04-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210403_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_doctor',
        ),
    ]
