# Generated by Django 2.2 on 2021-05-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Doctor')),
            ],
        ),
    ]
